### ISSUE TITLE
Roadmap: GAT of GATs

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#165]
@epatters @mehalter @bosonbaas, here are some tasks I think we should address for the next push on Catlab (aka Gatlab).

- [ ] CT constructions
    - [ ] Product/Sum
    - [ ] Span/Cospan
    - [ ] Functor/Instance
    - [ ] Category of Elements
- [ ] GAT Functors, injective, surjective to talk about relationships between algebraic theories
    - [ ] Causal Theories
    - [ ] Statistical Theories
    - [ ] Physical Theories
- [ ] Compute pushout/pullback of GAT functors
    - [ ] Cospan category for open GATs
- [ ] Pushout/pullback within a Cat, can we infer the rules for composition of FinSet cospans from the definition of FinSet morphisms?
- [ ] Relation orient computing: functors from an arbitrary GAT into Rel
- [ ] Generic Operads
  - [ ] Syntax
  - [ ] Drawing
  - [ ] Substitution based on term matching
- [ ] Axiom Support
  - [ ] Generating term rewriting rules from the specification of the axioms of a GAT

**Comment by mehalter** [comment]
- [ ] Task 0: Refactor SemanticModels -> (Catlab.jl, AlgebraicX.jl)
- [ ] Task 1: Refactor Catlab.jl implementation of GAT to provide more efficient and easier to work with data structures
